### ISSUE TITLE
Is EventDisplayClose wired up?

### ISSUE THREAD

**Issue by SolarLune** [Fryguy/crystal_allegro#1]
Hey, there!

So I just started trying this out, and it seems pretty interesting. I was wondering if I'm doing something wrong, or if EventDisplayClose isn't wired up correctly? Seems like it's not generating an event - here's my test:

```crystal
require "crystal_allegro"
require "./Test/*"

module Test

  CrystalAllegro.init

  LibAllegro.install_keyboard()
  LibAllegro.install_mouse()
  LibAllegro.install_joystick()

  LibAllegro.create_display(640, 480)

  eventQueue = LibAllegro.create_event_queue()
  LibAllegro.register_event_source(eventQueue, LibAllegro.get_keyboard_event_source())
  LibAllegro.register_event_source(eventQueue, LibAllegro.get_mouse_event_source())
  LibAllegro.register_event_source(eventQueue, LibAllegro.get_joystick_event_source())

  playing = true

  while playing

    event = LibAllegro::Event.new
    
    while LibAllegro.peek_next_event(eventQueue, pointerof(event)) > 0

      LibAllegro.get_next_event(eventQueue, pointerof(event))

      puts(event.type)

      if event.type == LibAllegro::EventDisplayClose
        
        playing = false

      end

    end

    LibAllegro.clear_to_color(LibAllegro.map_rgba(255, 0, 0, 0))

    LibAllegro.flip_display()

  end
  
end

```

**Comment by Fryguy** [comment]
Thanks for trying out crystal_allegro, @SolarLune!  I am actively changing this and haven't released it yet, so expect changes as I rip through the examples and verify things work (also finding some issue in Crystal and crystal-lib, which is fun 😄)

---

In your example, the problem is that you didn't create a sink for a display_event_source, which is the event source that will emit that particular event.  To fix it, change your create_display line to:

```crystal
display = LibAllegro.create_display(640, 480)
```

and add a line for the event source

```crystal
LibAllegro.register_event_source(eventQueue, LibAllegro.get_display_event_source(display))
```

You can see an example of this in examples/ex_bitmap.cr.

**Comment by SolarLune** [comment]
Ah, that must be what I missed. Thanks for the reply!

**Comment by Fryguy** [comment]
I've pushed a better example in examples/ex_display_events.cr
